# Generated by Django 3.0.6 on 2020-05-15 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_no', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('blood_group', models.CharField(max_length=3)),
                ('case', models.TextField()),
                ('report', models.ImageField(blank=True, upload_to='accounts/patient_reports')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
